language: node_js
node_js:
  - '8'

before_install:
- openssl aes-256-cbc -K $encrypted_838aec5c1dde_key -iv $encrypted_838aec5c1dde_iv
  -in travis.enc -out travis -d

install:
  - npm install hexo-cli -g
  - npm install

deploy:
  provider: script
  skip_cleanup: true
  script: ./deploy.sh
  on:
    branch: master
